import { Book } from '../interfaces/index';

export const mockBooks: Book[] = [
  {
    id: 1,
    bookName: 'Thus Spoke Zarathustra',
    bookGenre: 'Philosophical',
    pageCount: 327,
    bookAuthorName: 'Friedrich Nietzsche',
    isbnNumber: '9780521602617',
  },
  {
    id: 2,
    bookName: 'Beyond good and evil',
    bookGenre: 'Philosophical',
    pageCount: 301,
    bookAuthorName: 'Friedrich Nietzsche',
    isbnNumber: '9780394703374',
  },
  {
    id: 3,
    bookName: 'God is dead',
    bookGenre: 'Philosophical',
    pageCount: 315,
    bookAuthorName: 'Friedrich Nietzsche',
    isbnNumber: '9789703207824',
  },
  {
    id: 4,
    bookName: 'World as Will & Idea',
    bookGenre: 'Philosophical',
    pageCount: 336,
    bookAuthorName: 'Arthur Schopenhauer',
    isbnNumber: '9780460875059',
  },
  {
    id: 5,
    bookName: 'The World as Will and Representation, Vol. 1',
    bookGenre: 'Philosophical',
    pageCount: 694,
    bookAuthorName: 'Arthur Schopenhauer',
    isbnNumber: '9780486217611',
  },
  {
    id: 6,
    bookName: 'Being and Time',
    bookGenre: 'Philosophical',
    pageCount: 354,
    bookAuthorName: 'Martin Heidegger',
    isbnNumber: '9780631101901',
  },
  {
    id: 7,
    bookName: 'Logic: The Question of Truth',
    bookGenre: 'Philosophical',
    pageCount: 376,
    bookAuthorName: 'Martin Heidegger',
    isbnNumber: '9780253021656',
  },
];
